//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesafioHexagonal.Dominio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesafioHexagonal.Dominio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data {0} não pode ser maior que a data atual..
        /// </summary>
        internal static string DataFuturaProibida {
            get {
                return ResourceManager.GetString("DataFuturaProibida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data {1} não pode ser maior ou igual a data {0}..
        /// </summary>
        internal static string DataInicioFimInvalidas {
            get {
                return ResourceManager.GetString("DataInicioFimInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data {0} inválida..
        /// </summary>
        internal static string DataInvalida {
            get {
                return ResourceManager.GetString("DataInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDD inválido..
        /// </summary>
        internal static string DddInvalido {
            get {
                return ResourceManager.GetString("DddInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail preenchido incorretamente..
        /// </summary>
        internal static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?:[a-z0-9!#$%&amp;&apos;*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&amp;&apos;*+/=?^_`{|}~-]+)*|&quot;(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*&quot;)@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\]).
        /// </summary>
        internal static string EmailRegex {
            get {
                return ResourceManager.GetString("EmailRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser preenchido..
        /// </summary>
        internal static string NaoPreenchido {
            get {
                return ResourceManager.GetString("NaoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de telefone inválido..
        /// </summary>
        internal static string NumeroTelefoneInvalido {
            get {
                return ResourceManager.GetString("NumeroTelefoneInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação do histórico inválida..
        /// </summary>
        internal static string SituacaoHistoricoInvalida {
            get {
                return ResourceManager.GetString("SituacaoHistoricoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de {0} inválido..
        /// </summary>
        internal static string UrlInvalida {
            get {
                return ResourceManager.GetString("UrlInvalida", resourceCulture);
            }
        }
    }
}
